// from https://brandcolors.net/
const brands = [
  // === Tech Giants ===
  { name:"Apple", industry:"Tech", colors:[{name:"Black",hex:"#000000"},{name:"Silver",hex:"#A2AAAD"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Microsoft", industry:"Tech", colors:[{name:"Red",hex:"#F25022"},{name:"Green",hex:"#7FBA00"},{name:"Blue",hex:"#00A4EF"},{name:"Yellow",hex:"#FFB900"}]},
  { name:"Google", industry:"Tech", colors:[{name:"Blue",hex:"#4285F4"},{name:"Red",hex:"#EA4335"},{name:"Yellow",hex:"#FBBC04"},{name:"Green",hex:"#34A853"}]},
  { name:"Amazon", industry:"E-commerce", colors:[{name:"Orange",hex:"#FF9900"},{name:"Dark Blue",hex:"#232F3E"},{name:"Black",hex:"#000000"}]},
  { name:"NVIDIA", industry:"Tech", colors:[{name:"Green",hex:"#76B900"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Meta", industry:"Social", colors:[{name:"Blue",hex:"#0668E1"},{name:"Light Blue",hex:"#58A6FF"},{name:"Dark",hex:"#1C2B33"}]},
  { name:"Samsung", industry:"Tech", colors:[{name:"Blue",hex:"#1428A0"},{name:"White",hex:"#FFFFFF"},{name:"Black",hex:"#000000"}]},
  { name:"TSMC", industry:"Tech", colors:[{name:"Red",hex:"#CC0000"},{name:"Dark Gray",hex:"#333333"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Broadcom", industry:"Tech", colors:[{name:"Red",hex:"#CC092F"},{name:"Dark",hex:"#1A1A2E"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Oracle", industry:"Tech", colors:[{name:"Red",hex:"#F80000"},{name:"Black",hex:"#312D2A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Tesla", industry:"Automotive", colors:[{name:"Red",hex:"#CC0000"},{name:"Silver",hex:"#C0C0C0"},{name:"Black",hex:"#000000"}]},
  { name:"Intel", industry:"Tech", colors:[{name:"Blue",hex:"#0071C5"},{name:"Light Blue",hex:"#00AEEF"},{name:"White",hex:"#FFFFFF"}]},
  { name:"AMD", industry:"Tech", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"IBM", industry:"Tech", colors:[{name:"Blue",hex:"#0F62FE"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#161616"}]},
  { name:"Cisco", industry:"Tech", colors:[{name:"Blue",hex:"#049FD9"},{name:"Dark Blue",hex:"#00BCEB"},{name:"Dark",hex:"#1B1C1D"}]},
  { name:"Adobe", industry:"Design", colors:[{name:"Red",hex:"#FF0000"},{name:"Dark",hex:"#2C2C2C"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Salesforce", industry:"Tech", colors:[{name:"Blue",hex:"#00A1E0"},{name:"Dark Blue",hex:"#032D60"},{name:"White",hex:"#FFFFFF"}]},
  { name:"SAP", industry:"Tech", colors:[{name:"Blue",hex:"#0070F2"},{name:"Gold",hex:"#F0AB00"},{name:"Dark",hex:"#1D2D3E"}]},
  { name:"Netflix", industry:"Entertainment", colors:[{name:"Red",hex:"#E50914"},{name:"Black",hex:"#141414"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Qualcomm", industry:"Tech", colors:[{name:"Blue",hex:"#3253DC"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A2E"}]},
  { name:"Dell", industry:"Tech", colors:[{name:"Blue",hex:"#007DB8"},{name:"Dark",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"HP", industry:"Tech", colors:[{name:"Blue",hex:"#0096D6"},{name:"Dark",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Lenovo", industry:"Tech", colors:[{name:"Red",hex:"#E2231A"},{name:"Dark",hex:"#333333"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Sony", industry:"Tech", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"LG", industry:"Tech", colors:[{name:"Red",hex:"#A50034"},{name:"Gray",hex:"#6B6B6B"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Panasonic", industry:"Tech", colors:[{name:"Blue",hex:"#0064B4"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Philips", industry:"Tech", colors:[{name:"Blue",hex:"#0B5ED7"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Toshiba", industry:"Tech", colors:[{name:"Red",hex:"#FF0000"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#333333"}]},
  { name:"Xiaomi", industry:"Tech", colors:[{name:"Orange",hex:"#FF6900"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Huawei", industry:"Tech", colors:[{name:"Red",hex:"#CF0A2C"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#000000"}]},
  { name:"Oppo", industry:"Tech", colors:[{name:"Green",hex:"#1BA784"},{name:"Dark",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"OnePlus", industry:"Tech", colors:[{name:"Red",hex:"#EB0028"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Palantir", industry:"Tech", colors:[{name:"Black",hex:"#101113"},{name:"White",hex:"#FFFFFF"},{name:"Blue",hex:"#2F3B4E"}]},
  { name:"Chrome", industry:"Tech", colors:[{name:"Blue",hex:"#4285F4"},{name:"Red",hex:"#EA4335"},{name:"Yellow",hex:"#FBBC04"},{name:"Green",hex:"#34A853"}]},
  { name:"Safari", industry:"Tech", colors:[{name:"Blue",hex:"#006CFF"},{name:"Red",hex:"#FF3B30"},{name:"White",hex:"#FFFFFF"}]},
  // === Social & Communication ===
  { name:"Twitter/X", industry:"Social", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Instagram", industry:"Social", colors:[{name:"Purple",hex:"#833AB4"},{name:"Pink",hex:"#E1306C"},{name:"Orange",hex:"#F77737"},{name:"Yellow",hex:"#FCAF45"}]},
  { name:"LinkedIn", industry:"Social", colors:[{name:"Blue",hex:"#0A66C2"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"TikTok", industry:"Social", colors:[{name:"Black",hex:"#010101"},{name:"Cyan",hex:"#25F4EE"},{name:"Red",hex:"#FE2C55"}]},
  { name:"Snapchat", industry:"Social", colors:[{name:"Yellow",hex:"#FFFC00"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"WhatsApp", industry:"Social", colors:[{name:"Green",hex:"#25D366"},{name:"Teal",hex:"#128C7E"},{name:"Dark Teal",hex:"#075E54"}]},
  { name:"Telegram", industry:"Social", colors:[{name:"Blue",hex:"#0088CC"},{name:"Light Blue",hex:"#34ACE0"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Discord", industry:"Social", colors:[{name:"Blurple",hex:"#5865F2"},{name:"Green",hex:"#57F287"},{name:"Yellow",hex:"#FEE75C"},{name:"Fuchsia",hex:"#EB459E"}]},
  { name:"Pinterest", industry:"Social", colors:[{name:"Red",hex:"#E60023"},{name:"White",hex:"#FFFFFF"},{name:"Black",hex:"#000000"}]},
  { name:"Reddit", industry:"Social", colors:[{name:"Orange Red",hex:"#FF4500"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Signal", industry:"Social", colors:[{name:"Blue",hex:"#3A76F0"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1B1B1B"}]},
  { name:"WeChat", industry:"Social", colors:[{name:"Green",hex:"#09B83E"},{name:"Dark",hex:"#2E2E2E"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Line", industry:"Social", colors:[{name:"Green",hex:"#00C300"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Mastodon", industry:"Social", colors:[{name:"Purple",hex:"#6364FF"},{name:"Dark",hex:"#191B22"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Threads", industry:"Social", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Bluesky", industry:"Social", colors:[{name:"Blue",hex:"#0085FF"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#15171B"}]},
  { name:"BeReal", industry:"Social", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Clubhouse", industry:"Social", colors:[{name:"Yellow",hex:"#F2E359"},{name:"Brown",hex:"#553A1F"},{name:"White",hex:"#FFFFFF"}]},
  // === Streaming & Entertainment ===
  { name:"Disney+", industry:"Entertainment", colors:[{name:"Dark Teal",hex:"#00212F"},{name:"Teal",hex:"#02636F"},{name:"White",hex:"#F9F9F9"}]},
  { name:"HBO Max", industry:"Entertainment", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Hulu", industry:"Entertainment", colors:[{name:"Green",hex:"#1CE783"},{name:"Dark",hex:"#040405"},{name:"Gray",hex:"#272C30"}]},
  { name:"Twitch", industry:"Entertainment", colors:[{name:"Purple",hex:"#9146FF"},{name:"Ice",hex:"#F0F0FF"},{name:"Dark",hex:"#0E0E10"}]},
  { name:"YouTube", industry:"Entertainment", colors:[{name:"Red",hex:"#FF0000"},{name:"Black",hex:"#282828"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Paramount+", industry:"Entertainment", colors:[{name:"Blue",hex:"#0064FF"},{name:"Dark",hex:"#00004D"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Peacock", industry:"Entertainment", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"},{name:"Feather Yellow",hex:"#FCB711"},{name:"Feather Orange",hex:"#F37021"},{name:"Feather Red",hex:"#CC004C"},{name:"Feather Purple",hex:"#6460AA"},{name:"Feather Blue",hex:"#0089D0"},{name:"Feather Green",hex:"#0DB14B"}]},
  // === Music ===
  { name:"Spotify", industry:"Music", colors:[{name:"Green",hex:"#1DB954"},{name:"Black",hex:"#191414"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Apple Music", industry:"Music", colors:[{name:"Red",hex:"#FA243C"},{name:"Pink",hex:"#FB5C74"},{name:"Black",hex:"#000000"}]},
  { name:"SoundCloud", industry:"Music", colors:[{name:"Orange",hex:"#FF5500"},{name:"Dark",hex:"#333333"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Tidal", industry:"Music", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Deezer", industry:"Music", colors:[{name:"Purple",hex:"#A238FF"},{name:"Dark",hex:"#191922"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Pandora", industry:"Music", colors:[{name:"Pink",hex:"#EC2A5E"},{name:"Purple",hex:"#8A1FB8"},{name:"Blue",hex:"#3668E7"}]},
  { name:"Bandcamp", industry:"Music", colors:[{name:"Teal",hex:"#1DA0C3"},{name:"Blue",hex:"#619AA9"},{name:"Dark",hex:"#1D1D1D"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Audiomack", industry:"Music", colors:[{name:"Orange",hex:"#FFA500"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Shazam", industry:"Music", colors:[{name:"Blue",hex:"#0088FF"},{name:"Dark",hex:"#0A0A0A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"iHeartRadio", industry:"Music", colors:[{name:"Red",hex:"#C6002B"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  // === Fintech & Finance ===
  { name:"Visa", industry:"Fintech", colors:[{name:"Blue",hex:"#1A1F71"},{name:"Gold",hex:"#F7B600"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Mastercard", industry:"Fintech", colors:[{name:"Red",hex:"#EB001B"},{name:"Orange",hex:"#FF5F00"},{name:"Yellow",hex:"#F79E1B"}]},
  { name:"PayPal", industry:"Fintech", colors:[{name:"Blue",hex:"#003087"},{name:"Light Blue",hex:"#009CDE"},{name:"Dark Blue",hex:"#012169"}]},
  { name:"Stripe", industry:"Fintech", colors:[{name:"Blurple",hex:"#635BFF"},{name:"Cyan",hex:"#00D4FF"},{name:"Navy",hex:"#0A2540"}]},
  { name:"Square", industry:"Fintech", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Robinhood", industry:"Fintech", colors:[{name:"Green",hex:"#00C805"},{name:"Dark",hex:"#1E2124"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Coinbase", industry:"Fintech", colors:[{name:"Blue",hex:"#0052FF"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#050F1E"}]},
  { name:"Revolut", industry:"Fintech", colors:[{name:"Black",hex:"#000000"},{name:"Blue",hex:"#0075EB"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Wise", industry:"Fintech", colors:[{name:"Green",hex:"#9FE870"},{name:"Navy",hex:"#163300"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Plaid", industry:"Fintech", colors:[{name:"Black",hex:"#111111"},{name:"Blue",hex:"#0073E6"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Klarna", industry:"Fintech", colors:[{name:"Pink",hex:"#FFB3C7"},{name:"Black",hex:"#0A0B09"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Affirm", industry:"Fintech", colors:[{name:"Blue",hex:"#4A4AF4"},{name:"Black",hex:"#0B0B0F"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Chime", industry:"Fintech", colors:[{name:"Green",hex:"#1EC677"},{name:"Dark",hex:"#14161A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Cash App", industry:"Fintech", colors:[{name:"Green",hex:"#00D632"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Venmo", industry:"Fintech", colors:[{name:"Blue",hex:"#008CFF"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A2E"}]},
  { name:"N26", industry:"Fintech", colors:[{name:"Teal",hex:"#36A18B"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Monzo", industry:"Fintech", colors:[{name:"Hot Coral",hex:"#FF4F40"},{name:"Lime",hex:"#BBF42E"},{name:"Teal",hex:"#48D3B2"},{name:"Navy",hex:"#14233C"}]},
  { name:"Nubank", industry:"Fintech", colors:[{name:"Purple",hex:"#820AD1"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Brex", industry:"Fintech", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Marqeta", industry:"Fintech", colors:[{name:"Indigo",hex:"#271E64"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#0E0E0E"}]},
  // === E-commerce ===
  { name:"Alibaba", industry:"E-commerce", colors:[{name:"Orange",hex:"#FF6A00"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Shopify", industry:"E-commerce", colors:[{name:"Green",hex:"#96BF48"},{name:"Dark Green",hex:"#5E8E3E"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#2A2725"}]},
  { name:"eBay", industry:"E-commerce", colors:[{name:"Red",hex:"#E53238"},{name:"Blue",hex:"#0064D2"},{name:"Yellow",hex:"#F5AF02"},{name:"Green",hex:"#86B817"}]},
  { name:"Etsy", industry:"E-commerce", colors:[{name:"Orange",hex:"#F56400"},{name:"Dark",hex:"#232347"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Wish", industry:"E-commerce", colors:[{name:"Blue",hex:"#2FB7EC"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A2E"}]},
  { name:"Wayfair", industry:"E-commerce", colors:[{name:"Purple",hex:"#7B0E8E"},{name:"Gold",hex:"#C09A5C"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Mercado Libre", industry:"E-commerce", colors:[{name:"Yellow",hex:"#FFE600"},{name:"Blue",hex:"#3483FA"},{name:"White",hex:"#FFFFFF"}]},
  { name:"JD.com", industry:"E-commerce", colors:[{name:"Red",hex:"#E2001A"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Zalando", industry:"E-commerce", colors:[{name:"Orange",hex:"#FF6900"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Rakuten", industry:"E-commerce", colors:[{name:"Red",hex:"#BF0000"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#333333"}]},
  { name:"Shopify Plus", industry:"E-commerce", colors:[{name:"Black",hex:"#000000"},{name:"Lime",hex:"#95C11F"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Coupang", industry:"E-commerce", colors:[{name:"Red",hex:"#E02020"},{name:"Blue",hex:"#0050A0"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Pinduoduo", industry:"E-commerce", colors:[{name:"Red",hex:"#E02020"},{name:"Orange",hex:"#FF6900"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Temu", industry:"E-commerce", colors:[{name:"Orange",hex:"#FF6900"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Shein", industry:"E-commerce", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"},{name:"Red",hex:"#E41A1F"}]},
  { name:"ThredUp", industry:"E-commerce", colors:[{name:"Black",hex:"#000000"},{name:"Pale Green",hex:"#DAEFC6"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Poshmark", industry:"E-commerce", colors:[{name:"Burgundy",hex:"#822432"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Depop", industry:"E-commerce", colors:[{name:"Red",hex:"#FF2300"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"StockX", industry:"E-commerce", colors:[{name:"Green",hex:"#08A05C"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Farfetch", industry:"E-commerce", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"ASOS", industry:"E-commerce", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  // === Retail ===
  { name:"Walmart", industry:"Retail", colors:[{name:"Blue",hex:"#0071DC"},{name:"Yellow",hex:"#FFC220"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Target", industry:"Retail", colors:[{name:"Red",hex:"#CC0000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Costco", industry:"Retail", colors:[{name:"Red",hex:"#E31837"},{name:"Blue",hex:"#005DAA"},{name:"White",hex:"#FFFFFF"}]},
  { name:"IKEA", industry:"Retail", colors:[{name:"Blue",hex:"#0058A3"},{name:"Yellow",hex:"#FFDA1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Home Depot", industry:"Retail", colors:[{name:"Orange",hex:"#F96302"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Lowe's", industry:"Retail", colors:[{name:"Blue",hex:"#004990"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Best Buy", industry:"Retail", colors:[{name:"Blue",hex:"#0046BE"},{name:"Yellow",hex:"#FFE000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Sephora", industry:"Retail", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"CVS", industry:"Retail", colors:[{name:"Red",hex:"#CC0000"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Walgreens", industry:"Retail", colors:[{name:"Red",hex:"#E31837"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Kroger", industry:"Retail", colors:[{name:"Blue",hex:"#0049A0"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Whole Foods", industry:"Retail", colors:[{name:"Green",hex:"#00674B"},{name:"Dark",hex:"#1A3C34"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Trader Joe's", industry:"Retail", colors:[{name:"Red",hex:"#DA291C"},{name:"White",hex:"#FFFFFF"},{name:"Brown",hex:"#6B3A19"}]},
  { name:"Nordstrom", industry:"Retail", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"},{name:"Gray",hex:"#888888"}]},
  { name:"Macy's", industry:"Retail", colors:[{name:"Red",hex:"#E01B22"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"TJ Maxx", industry:"Retail", colors:[{name:"Red",hex:"#CC0000"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Ross", industry:"Retail", colors:[{name:"Blue",hex:"#0081C6"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Dollar General", industry:"Retail", colors:[{name:"Yellow",hex:"#FFCC00"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Five Below", industry:"Retail", colors:[{name:"Blue",hex:"#0074C8"},{name:"Yellow",hex:"#FFE200"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Aldi", industry:"Retail", colors:[{name:"Blue",hex:"#003D8F"},{name:"Red",hex:"#CC0000"},{name:"Orange",hex:"#FF6600"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Lidl", industry:"Retail", colors:[{name:"Blue",hex:"#0050AA"},{name:"Red",hex:"#E3000F"},{name:"Yellow",hex:"#FFD700"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Tesco", industry:"Retail", colors:[{name:"Blue",hex:"#005BAB"},{name:"Red",hex:"#EE1C25"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Carrefour", industry:"Retail", colors:[{name:"Blue",hex:"#004A97"},{name:"Red",hex:"#CC0000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"7-Eleven", industry:"Retail", colors:[{name:"Green",hex:"#007A33"},{name:"Red",hex:"#D41B2C"},{name:"Orange",hex:"#F37021"},{name:"White",hex:"#FFFFFF"}]},
  // === Travel ===
  { name:"Airbnb", industry:"Travel", colors:[{name:"Rausch",hex:"#FF385C"},{name:"Dark",hex:"#222222"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Booking.com", industry:"Travel", colors:[{name:"Blue",hex:"#003580"},{name:"Light Blue",hex:"#009FE3"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Expedia", industry:"Travel", colors:[{name:"Yellow",hex:"#FBCE00"},{name:"Blue",hex:"#00355F"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Tripadvisor", industry:"Travel", colors:[{name:"Green",hex:"#34E0A1"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Kayak", industry:"Travel", colors:[{name:"Orange",hex:"#FF690F"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Hopper", industry:"Travel", colors:[{name:"Coral",hex:"#FA6866"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Hotels.com", industry:"Travel", colors:[{name:"Red",hex:"#D80229"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Vrbo", industry:"Travel", colors:[{name:"Blue",hex:"#0A5EAA"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Skyscanner", industry:"Travel", colors:[{name:"Blue",hex:"#0770E3"},{name:"Cyan",hex:"#00B9F1"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Hostelworld", industry:"Travel", colors:[{name:"Orange",hex:"#F25621"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"GetYourGuide", industry:"Travel", colors:[{name:"Red",hex:"#FF5533"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Marriott", industry:"Travel", colors:[{name:"Red",hex:"#A5091E"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Hilton", industry:"Travel", colors:[{name:"Blue",hex:"#003580"},{name:"Light Blue",hex:"#0085C3"},{name:"White",hex:"#FFFFFF"}]},
  { name:"IHG", industry:"Travel", colors:[{name:"Deep Teal",hex:"#1F4456"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Hyatt Hotels", industry:"Travel", colors:[{name:"Blue",hex:"#0072CE"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Delta Airlines", industry:"Travel", colors:[{name:"Red",hex:"#E51937"},{name:"Blue",hex:"#003087"},{name:"White",hex:"#FFFFFF"}]},
  { name:"United Airlines", industry:"Travel", colors:[{name:"Blue",hex:"#002244"},{name:"Light Blue",hex:"#009FDA"},{name:"White",hex:"#FFFFFF"}]},
  { name:"American Airlines", industry:"Travel", colors:[{name:"Red",hex:"#C30019"},{name:"Blue",hex:"#0078D2"},{name:"Silver",hex:"#9DA6AB"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Southwest Airlines", industry:"Travel", colors:[{name:"Blue",hex:"#304CB2"},{name:"Red",hex:"#CC0000"},{name:"Yellow",hex:"#FFBF27"},{name:"White",hex:"#FFFFFF"}]},
  { name:"JetBlue", industry:"Travel", colors:[{name:"Blue",hex:"#003876"},{name:"Light Blue",hex:"#00B2E3"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Ryanair", industry:"Travel", colors:[{name:"Blue",hex:"#073590"},{name:"Yellow",hex:"#F9C929"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Emirates", industry:"Travel", colors:[{name:"Red",hex:"#C8102E"},{name:"Gold",hex:"#B8A16A"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Singapore Airlines", industry:"Travel", colors:[{name:"Blue",hex:"#003087"},{name:"Gold",hex:"#C5A028"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Cathay Pacific", industry:"Travel", colors:[{name:"Green",hex:"#006564"},{name:"Dark",hex:"#003A3A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"British Airways", industry:"Travel", colors:[{name:"Blue",hex:"#075AAA"},{name:"Red",hex:"#EB2226"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Lufthansa", industry:"Travel", colors:[{name:"Blue",hex:"#05164D"},{name:"Yellow",hex:"#FFAD00"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Air France", industry:"Travel", colors:[{name:"Blue",hex:"#002F9B"},{name:"Red",hex:"#CC0000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Qatar Airways", industry:"Travel", colors:[{name:"Maroon",hex:"#5C0632"},{name:"White",hex:"#FFFFFF"},{name:"Silver",hex:"#AAAAAA"}]},
  // === Transport ===
  { name:"Uber", industry:"Transport", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Lyft", industry:"Transport", colors:[{name:"Pink",hex:"#FF00BF"},{name:"Black",hex:"#11111F"},{name:"White",hex:"#FFFFFF"}]},
  { name:"DoorDash", industry:"Transport", colors:[{name:"Red",hex:"#FF3008"},{name:"Dark",hex:"#191919"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Grab", industry:"Transport", colors:[{name:"Green",hex:"#00B14F"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Instacart", industry:"Transport", colors:[{name:"Green",hex:"#0AAD0A"},{name:"Carrot Orange",hex:"#FF7009"},{name:"Kale",hex:"#003D29"},{name:"White",hex:"#FFFFFF"}]},
  { name:"FedEx", industry:"Transport", colors:[{name:"Purple",hex:"#4D148C"},{name:"Orange",hex:"#FF6200"},{name:"White",hex:"#FFFFFF"}]},
  { name:"UPS", industry:"Transport", colors:[{name:"Brown",hex:"#351C15"},{name:"Gold",hex:"#FFB500"},{name:"White",hex:"#FFFFFF"}]},
  { name:"DHL", industry:"Transport", colors:[{name:"Yellow",hex:"#FFCC00"},{name:"Red",hex:"#D40511"},{name:"White",hex:"#FFFFFF"}]},
  { name:"USPS", industry:"Transport", colors:[{name:"Blue",hex:"#004B97"},{name:"Red",hex:"#D12229"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Lime", industry:"Transport", colors:[{name:"Green",hex:"#00D22E"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Bird", industry:"Transport", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Bolt", industry:"Transport", colors:[{name:"Green",hex:"#34D186"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Waze", industry:"Transport", colors:[{name:"Blue",hex:"#33CCFF"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Waymo", industry:"Transport", colors:[{name:"Green",hex:"#00E89D"},{name:"Blue",hex:"#0078FF"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Cruise", industry:"Transport", colors:[{name:"Orange",hex:"#FF5F02"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  // === Productivity & SaaS ===
  { name:"Slack", industry:"Productivity", colors:[{name:"Aubergine",hex:"#4A154B"},{name:"Blue",hex:"#36C5F0"},{name:"Green",hex:"#2EB67D"},{name:"Red",hex:"#E01E5A"},{name:"Yellow",hex:"#ECB22E"}]},
  { name:"Notion", industry:"Productivity", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"},{name:"Warm Gray",hex:"#E6E6E4"}]},
  { name:"Zoom", industry:"Productivity", colors:[{name:"Blue",hex:"#2D8CFF"},{name:"Dark Blue",hex:"#0B5CFF"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Dropbox", industry:"Productivity", colors:[{name:"Blue",hex:"#0061FF"},{name:"Dark",hex:"#1E1919"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Linear", industry:"Productivity", colors:[{name:"Purple",hex:"#5E6AD2"},{name:"Dark",hex:"#171723"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Asana", industry:"Productivity", colors:[{name:"Coral",hex:"#F06A6A"},{name:"Dark",hex:"#151B26"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Jira", industry:"Productivity", colors:[{name:"Blue",hex:"#0052CC"},{name:"Light Blue",hex:"#2684FF"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Confluence", industry:"Productivity", colors:[{name:"Blue",hex:"#0065FF"},{name:"Dark Blue",hex:"#172B4D"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Monday.com", industry:"Productivity", colors:[{name:"Red",hex:"#FF3D57"},{name:"Yellow",hex:"#FFCB00"},{name:"Green",hex:"#00CA72"},{name:"Dark",hex:"#333333"}]},
  { name:"Trello", industry:"Productivity", colors:[{name:"Blue",hex:"#0052CC"},{name:"Light Blue",hex:"#00C2E0"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Airtable", industry:"Productivity", colors:[{name:"Blue",hex:"#2D7FF9"},{name:"Yellow",hex:"#FCB400"},{name:"Red",hex:"#F82B60"},{name:"Cyan",hex:"#18BFFF"}]},
  { name:"Miro", industry:"Productivity", colors:[{name:"Yellow",hex:"#FFD02F"},{name:"Dark",hex:"#050038"},{name:"White",hex:"#FFFFFF"}]},
  { name:"1Password", industry:"Productivity", colors:[{name:"Blue",hex:"#0572EC"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Loom", industry:"Productivity", colors:[{name:"Purple",hex:"#625DF5"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#14131A"}]},
  { name:"Calendly", industry:"Productivity", colors:[{name:"Blue",hex:"#006BFF"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#0B3558"}]},
  { name:"Todoist", industry:"Productivity", colors:[{name:"Red",hex:"#E44332"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1F1F1F"}]},
  { name:"Grammarly", industry:"Productivity", colors:[{name:"Green",hex:"#15C39A"},{name:"Dark",hex:"#0A1628"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Raycast", industry:"Productivity", colors:[{name:"Red",hex:"#FF6363"},{name:"Dark",hex:"#14141A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Arc Browser", industry:"Productivity", colors:[{name:"Blue",hex:"#3170F9"},{name:"Red",hex:"#F04A4E"},{name:"Yellow",hex:"#F7C948"},{name:"Purple",hex:"#8E5CE6"}]},
  { name:"Brave", industry:"Productivity", colors:[{name:"Orange",hex:"#FB542B"},{name:"Purple",hex:"#3F3070"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Firefox", industry:"Productivity", colors:[{name:"Orange",hex:"#FF7139"},{name:"Yellow",hex:"#FFC900"},{name:"Purple",hex:"#592ACB"}]},
  // === Design & Creative ===
  { name:"Figma", industry:"Design", colors:[{name:"Red",hex:"#F24E1E"},{name:"Purple",hex:"#A259FF"},{name:"Blue",hex:"#1ABCFE"},{name:"Green",hex:"#0ACF83"}]},
  { name:"Canva", industry:"Design", colors:[{name:"Purple",hex:"#7D2AE8"},{name:"Cyan",hex:"#00C4CC"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Dribbble", industry:"Design", colors:[{name:"Pink",hex:"#EA4C89"},{name:"Dark",hex:"#2C2C2C"},{name:"Light",hex:"#F3F3F4"}]},
  { name:"Behance", industry:"Design", colors:[{name:"Blue",hex:"#1769FF"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"InVision", industry:"Design", colors:[{name:"Pink",hex:"#FF3366"},{name:"Dark",hex:"#1B1B23"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Sketch", industry:"Design", colors:[{name:"Orange",hex:"#FDB300"},{name:"Brown",hex:"#EA6C00"},{name:"Dark",hex:"#1B1B1B"}]},
  { name:"Framer", industry:"Design", colors:[{name:"Blue",hex:"#0055FF"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Webflow", industry:"Design", colors:[{name:"Blue",hex:"#4353FF"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Wix", industry:"Design", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"},{name:"Blue",hex:"#116DFF"}]},
  { name:"Squarespace", industry:"Design", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  // === Developer Tools ===
  { name:"GitHub", industry:"Dev Tools", colors:[{name:"Black",hex:"#181717"},{name:"White",hex:"#FFFFFF"}]},
  { name:"GitLab", industry:"Dev Tools", colors:[{name:"Orange",hex:"#FC6D26"},{name:"Red",hex:"#E24329"},{name:"Yellow",hex:"#FCA326"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Vercel", industry:"Dev Tools", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Netlify", industry:"Dev Tools", colors:[{name:"Teal",hex:"#00C7B7"},{name:"Dark",hex:"#0E1E25"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Docker", industry:"Dev Tools", colors:[{name:"Blue",hex:"#2496ED"},{name:"Dark",hex:"#003F8C"},{name:"White",hex:"#FFFFFF"}]},
  { name:"npm", industry:"Dev Tools", colors:[{name:"Red",hex:"#CB3837"},{name:"Dark",hex:"#333333"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Stack Overflow", industry:"Dev Tools", colors:[{name:"Orange",hex:"#F48024"},{name:"Dark",hex:"#242729"},{name:"Gray",hex:"#BCBBBB"}]},
  { name:"Supabase", industry:"Dev Tools", colors:[{name:"Green",hex:"#3ECF8E"},{name:"Dark",hex:"#1C1C1C"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Datadog", industry:"Dev Tools", colors:[{name:"Purple",hex:"#632CA6"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Cloudflare", industry:"Dev Tools", colors:[{name:"Orange",hex:"#F48120"},{name:"Dark",hex:"#404040"},{name:"White",hex:"#FFFFFF"}]},
  { name:"MongoDB", industry:"Dev Tools", colors:[{name:"Green",hex:"#00ED64"},{name:"Dark Green",hex:"#001E2B"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Redis", industry:"Dev Tools", colors:[{name:"Red",hex:"#DC382D"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Elastic", industry:"Dev Tools", colors:[{name:"Yellow",hex:"#FEC514"},{name:"Pink",hex:"#F04E98"},{name:"Teal",hex:"#00BFB3"},{name:"Blue",hex:"#0077CC"}]},
  { name:"Terraform", industry:"Dev Tools", colors:[{name:"Purple",hex:"#7B42BC"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Kubernetes", industry:"Dev Tools", colors:[{name:"Blue",hex:"#326CE5"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Sentry", industry:"Dev Tools", colors:[{name:"Purple",hex:"#362D59"},{name:"Red",hex:"#E1567C"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Postman", industry:"Dev Tools", colors:[{name:"Orange",hex:"#FF6C37"},{name:"Dark",hex:"#212121"},{name:"White",hex:"#FFFFFF"}]},
  { name:"WordPress", industry:"Dev Tools", colors:[{name:"Blue",hex:"#21759B"},{name:"Gray",hex:"#464646"},{name:"Light",hex:"#EEEEEE"}]},
  { name:"Twilio", industry:"Dev Tools", colors:[{name:"Red",hex:"#F22F46"},{name:"Dark",hex:"#121C2D"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Okta", industry:"Dev Tools", colors:[{name:"Black",hex:"#191919"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Auth0", industry:"Dev Tools", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"LaunchDarkly", industry:"Dev Tools", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Heroku", industry:"Dev Tools", colors:[{name:"Purple",hex:"#6762A6"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Fly.io", industry:"Dev Tools", colors:[{name:"Purple",hex:"#7C3AED"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"PlanetScale", industry:"Dev Tools", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"},{name:"Gray",hex:"#888888"}]},
  { name:"Neon", industry:"Dev Tools", colors:[{name:"Green",hex:"#00E599"},{name:"Dark",hex:"#0D0D0D"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Turso", industry:"Dev Tools", colors:[{name:"Teal",hex:"#4FF8D2"},{name:"Dark",hex:"#0A0A0A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Deno", industry:"Dev Tools", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"},{name:"Green",hex:"#70FFAF"}]},
  { name:"Bun", industry:"Dev Tools", colors:[{name:"Peach",hex:"#FBF0DF"},{name:"Brown",hex:"#B5584E"},{name:"Dark",hex:"#14151A"}]},
  { name:"Rust", industry:"Dev Tools", colors:[{name:"Orange",hex:"#CE412B"},{name:"Dark",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Go", industry:"Dev Tools", colors:[{name:"Cyan",hex:"#00ADD8"},{name:"Dark",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Python", industry:"Dev Tools", colors:[{name:"Blue",hex:"#3776AB"},{name:"Yellow",hex:"#FFD43B"},{name:"White",hex:"#FFFFFF"}]},
  // === Marketing ===
  { name:"Mailchimp", industry:"Marketing", colors:[{name:"Cavendish",hex:"#FFE01B"},{name:"Peppercorn",hex:"#241C15"},{name:"Coconut",hex:"#EFEEEA"}]},
  { name:"HubSpot", industry:"Marketing", colors:[{name:"Orange",hex:"#FF7A59"},{name:"Dark",hex:"#2D3E50"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Intercom", industry:"Marketing", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Zendesk", industry:"Marketing", colors:[{name:"Kale",hex:"#03363D"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Segment", industry:"Marketing", colors:[{name:"Red",hex:"#F22F46"},{name:"Dark",hex:"#1A1A2E"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Mixpanel", industry:"Marketing", colors:[{name:"Purple",hex:"#7856FF"},{name:"Dark",hex:"#1B0B3B"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Amplitude", industry:"Marketing", colors:[{name:"Blue",hex:"#1E61F0"},{name:"Dark",hex:"#0B1120"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Klaviyo", industry:"Marketing", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Braze", industry:"Marketing", colors:[{name:"Purple",hex:"#801ED7"},{name:"Dark Purple",hex:"#300266"},{name:"White",hex:"#FFFFFF"}]},
  { name:"SendGrid", industry:"Marketing", colors:[{name:"Red",hex:"#F22F46"},{name:"Dark",hex:"#1C1C1C"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Hootsuite", industry:"Marketing", colors:[{name:"Red",hex:"#FF4C46"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Buffer", industry:"Marketing", colors:[{name:"Blue",hex:"#168EEA"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Sprout Social", industry:"Marketing", colors:[{name:"Green",hex:"#59CB59"},{name:"Dark",hex:"#293340"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Later", industry:"Marketing", colors:[{name:"Black",hex:"#000000"},{name:"Cream",hex:"#F8F2EA"}]},
  { name:"Semrush", industry:"Marketing", colors:[{name:"Orange",hex:"#FF642D"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Ahrefs", industry:"Marketing", colors:[{name:"Blue",hex:"#1166EE"},{name:"Orange",hex:"#FF6C00"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Moz", industry:"Marketing", colors:[{name:"Blue",hex:"#1779BA"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  // === Education ===
  { name:"Duolingo", industry:"Education", colors:[{name:"Feather Green",hex:"#58CC02"},{name:"Mask Green",hex:"#89E219"},{name:"Macaw Blue",hex:"#1CB0F6"},{name:"Fox Orange",hex:"#FF9600"}]},
  { name:"Coursera", industry:"Education", colors:[{name:"Blue",hex:"#0056D2"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1F1F1F"}]},
  { name:"Khan Academy", industry:"Education", colors:[{name:"Green",hex:"#14BF96"},{name:"Blue",hex:"#1865F2"},{name:"Dark",hex:"#21242C"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Udemy", industry:"Education", colors:[{name:"Purple",hex:"#A435F0"},{name:"Dark",hex:"#1C1D1F"},{name:"White",hex:"#FFFFFF"}]},
  { name:"edX", industry:"Education", colors:[{name:"Ink",hex:"#02262B"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Skillshare", industry:"Education", colors:[{name:"Green",hex:"#00FF84"},{name:"Dark",hex:"#002333"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Codecademy", industry:"Education", colors:[{name:"Navy",hex:"#10162F"},{name:"Yellow",hex:"#FFD300"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Brilliant", industry:"Education", colors:[{name:"Green",hex:"#00C853"},{name:"Dark",hex:"#1A1A1A"},{name:"Orange",hex:"#FF9100"}]},
  { name:"Chegg", industry:"Education", colors:[{name:"Orange",hex:"#F96B14"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Quizlet", industry:"Education", colors:[{name:"Blue",hex:"#4255FF"},{name:"Twilight",hex:"#282E3E"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Canvas LMS", industry:"Education", colors:[{name:"Red",hex:"#E03C31"},{name:"Dark",hex:"#2D3B45"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Blackboard", industry:"Education", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Pluralsight", industry:"Education", colors:[{name:"Pink",hex:"#EC008C"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"LinkedIn Learning", industry:"Education", colors:[{name:"Blue",hex:"#0A66C2"},{name:"Dark",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"MasterClass", industry:"Education", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Kahoot", industry:"Education", colors:[{name:"Purple",hex:"#46178F"},{name:"Red",hex:"#E21B3C"},{name:"Blue",hex:"#1368CE"},{name:"Yellow",hex:"#FFA602"}]},
  // === Gaming ===
  { name:"PlayStation", industry:"Gaming", colors:[{name:"Blue",hex:"#003791"},{name:"White",hex:"#FFFFFF"},{name:"Black",hex:"#000000"}]},
  { name:"Xbox", industry:"Gaming", colors:[{name:"Green",hex:"#107C10"},{name:"White",hex:"#FFFFFF"},{name:"Black",hex:"#000000"}]},
  { name:"Nintendo", industry:"Gaming", colors:[{name:"Red",hex:"#E4000F"},{name:"White",hex:"#FFFFFF"},{name:"Gray",hex:"#8F8F8F"}]},
  { name:"Steam", industry:"Gaming", colors:[{name:"Dark Blue",hex:"#1B2838"},{name:"Blue",hex:"#66C0F4"},{name:"Dark",hex:"#171A21"}]},
  { name:"Epic Games", industry:"Gaming", colors:[{name:"Black",hex:"#2F2D2E"},{name:"White",hex:"#FFFFFF"},{name:"Blue",hex:"#0078F2"}]},
  { name:"Roblox", industry:"Gaming", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Unity", industry:"Gaming", colors:[{name:"Dark",hex:"#222C37"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Unreal Engine", industry:"Gaming", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"EA", industry:"Gaming", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Ubisoft", industry:"Gaming", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Activision", industry:"Gaming", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Riot Games", industry:"Gaming", colors:[{name:"Red",hex:"#D32936"},{name:"Dark",hex:"#111111"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Supercell", industry:"Gaming", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Mojang", industry:"Gaming", colors:[{name:"Red",hex:"#DB2331"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Valve", industry:"Gaming", colors:[{name:"Dark Blue",hex:"#171A21"},{name:"Blue",hex:"#66C0F4"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Bandai Namco", industry:"Gaming", colors:[{name:"Magenta",hex:"#E4007F"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Square Enix", industry:"Gaming", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"},{name:"Gold",hex:"#C4A24A"}]},
  { name:"Capcom", industry:"Gaming", colors:[{name:"Blue",hex:"#0033A0"},{name:"Yellow",hex:"#F9BE00"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Sega", industry:"Gaming", colors:[{name:"Blue",hex:"#17429E"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Blizzard", industry:"Gaming", colors:[{name:"Blue",hex:"#148EFF"},{name:"Gold",hex:"#F4B425"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Bungie", industry:"Gaming", colors:[{name:"Dark",hex:"#1C1C1C"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Bethesda", industry:"Gaming", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"CD Projekt Red", industry:"Gaming", colors:[{name:"Red",hex:"#CC0000"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Rockstar Games", industry:"Gaming", colors:[{name:"Yellow",hex:"#FCAF17"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Take-Two", industry:"Gaming", colors:[{name:"Black",hex:"#000000"},{name:"Blue",hex:"#0075BE"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Zynga", industry:"Gaming", colors:[{name:"Red",hex:"#E31836"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"King", industry:"Gaming", colors:[{name:"Crown Gold",hex:"#FFC400"},{name:"Orange",hex:"#FF9900"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Garena", industry:"Gaming", colors:[{name:"Red",hex:"#E41E26"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  // === Food & Beverage ===
  { name:"Coca-Cola", industry:"F&B", colors:[{name:"Red",hex:"#F40009"},{name:"White",hex:"#FFFFFF"},{name:"Black",hex:"#000000"}]},
  { name:"Pepsi", industry:"F&B", colors:[{name:"Electric Blue",hex:"#0E0E96"},{name:"Red",hex:"#FF1400"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Starbucks", industry:"F&B", colors:[{name:"Green",hex:"#00704A"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1E3932"}]},
  { name:"McDonald's", industry:"F&B", colors:[{name:"Red",hex:"#DA291C"},{name:"Yellow",hex:"#FFC72C"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Burger King", industry:"F&B", colors:[{name:"Red",hex:"#D62300"},{name:"Orange",hex:"#FF8732"},{name:"Brown",hex:"#502314"},{name:"Cream",hex:"#F5EBDC"}]},
  { name:"Subway", industry:"F&B", colors:[{name:"Green",hex:"#008C15"},{name:"Yellow",hex:"#FFD600"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Chipotle", industry:"F&B", colors:[{name:"Red",hex:"#A81612"},{name:"Brown",hex:"#441300"},{name:"Cream",hex:"#EDE0CF"}]},
  { name:"Domino's", industry:"F&B", colors:[{name:"Blue",hex:"#006491"},{name:"Red",hex:"#E31837"},{name:"White",hex:"#FFFFFF"}]},
  { name:"KFC", industry:"F&B", colors:[{name:"Red",hex:"#F40027"},{name:"White",hex:"#FFFFFF"},{name:"Black",hex:"#000000"}]},
  { name:"Dunkin'", industry:"F&B", colors:[{name:"Orange",hex:"#FF671F"},{name:"Pink",hex:"#DA1884"},{name:"Brown",hex:"#653819"}]},
  { name:"Red Bull", industry:"F&B", colors:[{name:"Blue",hex:"#223971"},{name:"Red",hex:"#CC1E4A"},{name:"Yellow",hex:"#FFC906"},{name:"Silver",hex:"#C0C0C0"}]},
  { name:"Monster Energy", industry:"F&B", colors:[{name:"Green",hex:"#95D600"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Taco Bell", industry:"F&B", colors:[{name:"Purple",hex:"#702082"},{name:"Pink",hex:"#D91A7C"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Wendy's", industry:"F&B", colors:[{name:"Red",hex:"#E2203D"},{name:"Yellow",hex:"#FFB640"},{name:"Blue",hex:"#009FDE"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Popeyes", industry:"F&B", colors:[{name:"Orange",hex:"#F15A22"},{name:"Red",hex:"#C8102E"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Chick-fil-A", industry:"F&B", colors:[{name:"Red",hex:"#E51636"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#004F71"}]},
  { name:"Krispy Kreme", industry:"F&B", colors:[{name:"Green",hex:"#006B3F"},{name:"Red",hex:"#C8102E"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Nestlé", industry:"F&B", colors:[{name:"Warm Gray",hex:"#63513D"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Kraft", industry:"F&B", colors:[{name:"Navy",hex:"#1E3D7C"},{name:"Red",hex:"#E21836"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Ben & Jerry's", industry:"F&B", colors:[{name:"Blue",hex:"#0066CC"},{name:"White",hex:"#FFFFFF"},{name:"Red",hex:"#CC0000"},{name:"Green",hex:"#009933"}]},
  { name:"Heineken", industry:"F&B", colors:[{name:"Green",hex:"#00A100"},{name:"Red",hex:"#FF2B06"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Budweiser", industry:"F&B", colors:[{name:"Red",hex:"#C8102E"},{name:"White",hex:"#FFFFFF"},{name:"Gold",hex:"#B5985A"}]},
  { name:"Guinness", industry:"F&B", colors:[{name:"Black",hex:"#000000"},{name:"Gold",hex:"#C5A867"},{name:"Cream",hex:"#F2E8D5"}]},
  { name:"Panda Express", industry:"F&B", colors:[{name:"Red",hex:"#CC0000"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Five Guys", industry:"F&B", colors:[{name:"Red",hex:"#CC0000"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Shake Shack", industry:"F&B", colors:[{name:"Green",hex:"#4DAF50"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"In-N-Out", industry:"F&B", colors:[{name:"Red",hex:"#DB2127"},{name:"Yellow",hex:"#F7D117"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Panera", industry:"F&B", colors:[{name:"Green",hex:"#2D6A2D"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Nando's", industry:"F&B", colors:[{name:"Red",hex:"#CC0000"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Tim Hortons", industry:"F&B", colors:[{name:"Red",hex:"#CC0000"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Costa Coffee", industry:"F&B", colors:[{name:"Red",hex:"#72212A"},{name:"Gold",hex:"#C5963A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Peet's Coffee", industry:"F&B", colors:[{name:"Coffee Brown",hex:"#4F2C1D"},{name:"Gold",hex:"#937031"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Blue Bottle", industry:"F&B", colors:[{name:"Blue",hex:"#0057A8"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Oatly", industry:"F&B", colors:[{name:"Light Blue",hex:"#9BCBEB"},{name:"Cream",hex:"#F5F0E8"},{name:"Black",hex:"#1A1A1A"}]},
  { name:"Beyond Meat", industry:"F&B", colors:[{name:"Green",hex:"#3D7B3F"},{name:"Red",hex:"#CC0000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Impossible Foods", industry:"F&B", colors:[{name:"Red",hex:"#E03131"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"General Mills", industry:"F&B", colors:[{name:"Blue",hex:"#003DA5"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Kellogg's", industry:"F&B", colors:[{name:"Red",hex:"#CC0000"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Mondelez", industry:"F&B", colors:[{name:"Purple",hex:"#5C2D91"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Mars", industry:"F&B", colors:[{name:"Blue",hex:"#0000A0"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Hershey's", industry:"F&B", colors:[{name:"Brown",hex:"#5C3317"},{name:"Silver",hex:"#C0C0C0"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Lindt", industry:"F&B", colors:[{name:"Navy",hex:"#002855"},{name:"Gold",hex:"#C5963A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Ferrero", industry:"F&B", colors:[{name:"Gold",hex:"#C5963A"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Jack Daniel's", industry:"F&B", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"},{name:"Gold",hex:"#C5963A"}]},
  { name:"Johnnie Walker", industry:"F&B", colors:[{name:"Gold",hex:"#C5963A"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Hennessy", industry:"F&B", colors:[{name:"Gold",hex:"#C5963A"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Moët", industry:"F&B", colors:[{name:"Gold",hex:"#C5963A"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Corona", industry:"F&B", colors:[{name:"Blue",hex:"#003399"},{name:"Gold",hex:"#FFD700"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Modelo", industry:"F&B", colors:[{name:"Gold",hex:"#C5963A"},{name:"Blue",hex:"#003399"},{name:"White",hex:"#FFFFFF"}]},
  // === Fashion & Luxury ===
  { name:"Nike", industry:"Fashion", colors:[{name:"Black",hex:"#111111"},{name:"White",hex:"#FFFFFF"},{name:"Orange",hex:"#FA5400"}]},
  { name:"Adidas", industry:"Fashion", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"},{name:"Blue",hex:"#0064B4"}]},
  { name:"Puma", industry:"Fashion", colors:[{name:"Red",hex:"#E41A1F"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Gucci", industry:"Fashion", colors:[{name:"Green",hex:"#006B3F"},{name:"Red",hex:"#C8102E"},{name:"Gold",hex:"#C4A265"},{name:"Black",hex:"#000000"}]},
  { name:"Louis Vuitton", industry:"Fashion", colors:[{name:"Brown",hex:"#6E4B2D"},{name:"Gold",hex:"#C5A253"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Hermès", industry:"Fashion", colors:[{name:"Orange",hex:"#F37021"},{name:"Brown",hex:"#6A3D0E"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Chanel", industry:"Fashion", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"},{name:"Gold",hex:"#C9B037"}]},
  { name:"Zara", industry:"Fashion", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"H&M", industry:"Fashion", colors:[{name:"Red",hex:"#E50010"},{name:"White",hex:"#FFFFFF"},{name:"Black",hex:"#000000"}]},
  { name:"Uniqlo", industry:"Fashion", colors:[{name:"Red",hex:"#FF0000"},{name:"White",hex:"#FFFFFF"},{name:"Black",hex:"#000000"}]},
  { name:"Lululemon", industry:"Fashion", colors:[{name:"Red",hex:"#D31334"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Patagonia", industry:"Fashion", colors:[{name:"Blue",hex:"#004F71"},{name:"White",hex:"#FFFFFF"},{name:"Orange",hex:"#F26522"}]},
  { name:"The North Face", industry:"Fashion", colors:[{name:"Red",hex:"#C8102E"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"New Balance", industry:"Fashion", colors:[{name:"Red",hex:"#CF0A2C"},{name:"Navy",hex:"#1D1D2C"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Under Armour", industry:"Fashion", colors:[{name:"Black",hex:"#1D1D1D"},{name:"Red",hex:"#E41C38"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Dior", industry:"Fashion", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"},{name:"Gold",hex:"#C9A96E"}]},
  { name:"Prada", industry:"Fashion", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"},{name:"Gold",hex:"#A8834F"}]},
  { name:"Versace", industry:"Fashion", colors:[{name:"Gold",hex:"#D4AF37"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Balenciaga", industry:"Fashion", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Burberry", industry:"Fashion", colors:[{name:"Knight Blue",hex:"#0006CF"},{name:"Tan",hex:"#C19A6B"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Ralph Lauren", industry:"Fashion", colors:[{name:"Navy",hex:"#041E42"},{name:"White",hex:"#FFFFFF"},{name:"Red",hex:"#A71930"}]},
  { name:"Calvin Klein", industry:"Fashion", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"},{name:"Gray",hex:"#999999"}]},
  { name:"Tommy Hilfiger", industry:"Fashion", colors:[{name:"Red",hex:"#C8102E"},{name:"Navy",hex:"#002D62"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Gap", industry:"Fashion", colors:[{name:"Navy",hex:"#002868"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Converse", industry:"Fashion", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"},{name:"Red",hex:"#C8102E"}]},
  { name:"Vans", industry:"Fashion", colors:[{name:"Red",hex:"#C1272D"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Reebok", industry:"Fashion", colors:[{name:"Red",hex:"#CC0000"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"ASICS", industry:"Fashion", colors:[{name:"Blue",hex:"#002D62"},{name:"Red",hex:"#E31837"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Fendi", industry:"Fashion", colors:[{name:"Yellow",hex:"#F9B000"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Moncler", industry:"Fashion", colors:[{name:"Dark Blue",hex:"#1A1A2E"},{name:"Red",hex:"#CC0000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Valentino", industry:"Fashion", colors:[{name:"Red",hex:"#CC0000"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Givenchy", industry:"Fashion", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Cartier", industry:"Fashion", colors:[{name:"Red",hex:"#B22222"},{name:"Gold",hex:"#C5963A"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Tiffany", industry:"Fashion", colors:[{name:"Tiffany Blue",hex:"#0ABAB5"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Rolex", industry:"Fashion", colors:[{name:"Green",hex:"#006039"},{name:"Gold",hex:"#C5963A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Omega", industry:"Fashion", colors:[{name:"Red",hex:"#C8102E"},{name:"Gold",hex:"#C5963A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Swatch", industry:"Fashion", colors:[{name:"Red",hex:"#CC0000"},{name:"White",hex:"#FFFFFF"},{name:"Black",hex:"#000000"}]},
  { name:"Fossil", industry:"Fashion", colors:[{name:"Dark",hex:"#1A1A1A"},{name:"Gold",hex:"#C5963A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Pandora Jewelry", industry:"Fashion", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Crocs", industry:"Fashion", colors:[{name:"Green",hex:"#80A343"},{name:"White",hex:"#FFFFFF"},{name:"Black",hex:"#000000"}]},
  { name:"Birkenstock", industry:"Fashion", colors:[{name:"Blue",hex:"#0067B1"},{name:"Tan",hex:"#C19A6B"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Dr. Martens", industry:"Fashion", colors:[{name:"Yellow",hex:"#FFD700"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Timberland", industry:"Fashion", colors:[{name:"Yellow",hex:"#FFB300"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Columbia Sportswear", industry:"Fashion", colors:[{name:"Blue",hex:"#003DA5"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Arc'teryx", industry:"Fashion", colors:[{name:"Black",hex:"#000000"},{name:"Gray",hex:"#888888"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Salomon", industry:"Fashion", colors:[{name:"Black",hex:"#000000"},{name:"Red",hex:"#CC0000"},{name:"White",hex:"#FFFFFF"}]},
  // === Automotive ===
  { name:"Toyota", industry:"Automotive", colors:[{name:"Red",hex:"#EB0A1E"},{name:"Gray",hex:"#58595B"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Mercedes-Benz", industry:"Automotive", colors:[{name:"Silver",hex:"#C0C0C0"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"BMW", industry:"Automotive", colors:[{name:"Blue",hex:"#1C69D4"},{name:"White",hex:"#FFFFFF"},{name:"Black",hex:"#000000"}]},
  { name:"Porsche", industry:"Automotive", colors:[{name:"Red",hex:"#D5001C"},{name:"Black",hex:"#000000"},{name:"Gold",hex:"#C4A24A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Ferrari", industry:"Automotive", colors:[{name:"Red",hex:"#DC0000"},{name:"Yellow",hex:"#FFCC00"},{name:"Black",hex:"#000000"}]},
  { name:"Lamborghini", industry:"Automotive", colors:[{name:"Gold",hex:"#DAA520"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Audi", industry:"Automotive", colors:[{name:"Black",hex:"#000000"},{name:"Silver",hex:"#AAAAAA"},{name:"Red",hex:"#BB0A30"}]},
  { name:"Ford", industry:"Automotive", colors:[{name:"Blue",hex:"#003478"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Rivian", industry:"Automotive", colors:[{name:"Yellow",hex:"#DEB843"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Lucid", industry:"Automotive", colors:[{name:"Dark",hex:"#0A0A0A"},{name:"Silver",hex:"#B8B8B8"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Volkswagen", industry:"Automotive", colors:[{name:"Blue",hex:"#001E50"},{name:"Silver",hex:"#C4C4C4"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Hyundai", industry:"Automotive", colors:[{name:"Blue",hex:"#002C5F"},{name:"Silver",hex:"#AAAAAA"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Kia", industry:"Automotive", colors:[{name:"Red",hex:"#BB162B"},{name:"Dark",hex:"#05141F"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Nissan", industry:"Automotive", colors:[{name:"Red",hex:"#C3002F"},{name:"Silver",hex:"#C0C0C0"},{name:"Black",hex:"#000000"}]},
  { name:"Honda", industry:"Automotive", colors:[{name:"Red",hex:"#CC0000"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Mazda", industry:"Automotive", colors:[{name:"Red",hex:"#910C0E"},{name:"Silver",hex:"#B5B5B5"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Volvo", industry:"Automotive", colors:[{name:"Blue",hex:"#003057"},{name:"Silver",hex:"#B5B5B5"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Jaguar", industry:"Automotive", colors:[{name:"Black",hex:"#000000"},{name:"Gold",hex:"#C69C6D"},{name:"Silver",hex:"#999999"}]},
  { name:"Land Rover", industry:"Automotive", colors:[{name:"Green",hex:"#005A2B"},{name:"Silver",hex:"#C0C0C0"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Subaru", industry:"Automotive", colors:[{name:"Blue",hex:"#013C74"},{name:"Silver",hex:"#B0B5B3"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Chevrolet", industry:"Automotive", colors:[{name:"Gold",hex:"#D4A843"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Genesis", industry:"Automotive", colors:[{name:"Black",hex:"#111111"},{name:"Copper",hex:"#A0714F"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Polestar", industry:"Automotive", colors:[{name:"Black",hex:"#000000"},{name:"Silver",hex:"#C0C0C0"},{name:"White",hex:"#FFFFFF"}]},
  { name:"BYD", industry:"Automotive", colors:[{name:"Red",hex:"#D70C19"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"NIO", industry:"Automotive", colors:[{name:"Blue",hex:"#00A0E9"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"XPeng", industry:"Automotive", colors:[{name:"Black",hex:"#000000"},{name:"Silver",hex:"#C0C0C0"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Li Auto", industry:"Automotive", colors:[{name:"Blue",hex:"#0050A0"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Bentley", industry:"Automotive", colors:[{name:"Dark Green",hex:"#1A3C34"},{name:"Silver",hex:"#C0C0C0"},{name:"Black",hex:"#000000"}]},
  { name:"Rolls-Royce", industry:"Automotive", colors:[{name:"Black",hex:"#000000"},{name:"Purple",hex:"#5A2D82"},{name:"Silver",hex:"#C0C0C0"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Maserati", industry:"Automotive", colors:[{name:"Blue",hex:"#1C3775"},{name:"Gold",hex:"#FFC845"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Alfa Romeo", industry:"Automotive", colors:[{name:"Red",hex:"#CC0000"},{name:"Blue",hex:"#001F5B"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Mini", industry:"Automotive", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Jeep", industry:"Automotive", colors:[{name:"Green",hex:"#1C6B2A"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Ram", industry:"Automotive", colors:[{name:"Dark",hex:"#1A1A1A"},{name:"Red",hex:"#CC0000"},{name:"Silver",hex:"#C0C0C0"}]},
  { name:"GMC", industry:"Automotive", colors:[{name:"Red",hex:"#CC0000"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Cadillac", industry:"Automotive", colors:[{name:"Black",hex:"#000000"},{name:"Silver",hex:"#C0C0C0"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Lincoln", industry:"Automotive", colors:[{name:"Dark",hex:"#1A1A1A"},{name:"Silver",hex:"#C0C0C0"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Acura", industry:"Automotive", colors:[{name:"Red",hex:"#CC0000"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Lexus", industry:"Automotive", colors:[{name:"Dark",hex:"#1A1A1A"},{name:"Silver",hex:"#C0C0C0"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Infiniti", industry:"Automotive", colors:[{name:"Dark",hex:"#1A1A1A"},{name:"Silver",hex:"#C0C0C0"},{name:"White",hex:"#FFFFFF"}]},
  // === Health & Wellness ===
  { name:"Peloton", industry:"Health", colors:[{name:"Red",hex:"#DF1C2F"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Fitbit", industry:"Health", colors:[{name:"Blue",hex:"#4285F4"},{name:"Red",hex:"#EA4335"},{name:"Yellow",hex:"#FBBC05"},{name:"Green",hex:"#34A853"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Headspace", industry:"Health", colors:[{name:"Orange",hex:"#F47D31"},{name:"Yellow",hex:"#FFE164"},{name:"Blue",hex:"#2B2A4C"}]},
  { name:"Calm", industry:"Health", colors:[{name:"Blue",hex:"#3A6EA5"},{name:"Dark Blue",hex:"#1E3D59"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Strava", industry:"Health", colors:[{name:"Orange",hex:"#FC4C02"},{name:"Dark",hex:"#2D2D32"},{name:"White",hex:"#FFFFFF"}]},
  { name:"MyFitnessPal", industry:"Health", colors:[{name:"Blue",hex:"#0075C9"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Noom", industry:"Health", colors:[{name:"Orange",hex:"#FF6900"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Oura", industry:"Health", colors:[{name:"Silver",hex:"#B5B5B5"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Whoop", industry:"Health", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Teladoc", industry:"Health", colors:[{name:"Purple",hex:"#4F2D7F"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"GoodRx", industry:"Health", colors:[{name:"Yellow",hex:"#FFD400"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Hims", industry:"Health", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Ro", industry:"Health", colors:[{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"},{name:"Blue",hex:"#0047BB"}]},
  { name:"One Medical", industry:"Health", colors:[{name:"Green",hex:"#00875A"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Garmin", industry:"Health", colors:[{name:"Blue",hex:"#007CC3"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Apple Health", industry:"Health", colors:[{name:"Pink",hex:"#FF2D55"},{name:"Red",hex:"#FF3B30"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Withings", industry:"Health", colors:[{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"},{name:"Blue",hex:"#0080FF"}]},
  { name:"AllTrails", industry:"Health", colors:[{name:"Green",hex:"#3D8A4E"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Nike Run Club", industry:"Health", colors:[{name:"Black",hex:"#000000"},{name:"Orange",hex:"#FA5400"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Map My Run", industry:"Health", colors:[{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  // === AI & ML ===
  { name:"OpenAI", industry:"AI", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Anthropic", industry:"AI", colors:[{name:"Tan",hex:"#D4A27F"},{name:"Dark",hex:"#191919"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Google DeepMind", industry:"AI", colors:[{name:"Blue",hex:"#4285F4"},{name:"Dark",hex:"#202124"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Midjourney", industry:"AI", colors:[{name:"White",hex:"#FFFFFF"},{name:"Black",hex:"#000000"}]},
  { name:"Hugging Face", industry:"AI", colors:[{name:"Yellow",hex:"#FFD21E"},{name:"Dark",hex:"#1A1A2E"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Stability AI", industry:"AI", colors:[{name:"Purple",hex:"#9B59B6"},{name:"Blue",hex:"#3498DB"},{name:"Dark",hex:"#1A1A2E"}]},
  { name:"Perplexity", industry:"AI", colors:[{name:"Teal",hex:"#20808D"},{name:"Dark",hex:"#191A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Replicate", industry:"AI", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Cohere", industry:"AI", colors:[{name:"Green",hex:"#355146"},{name:"Coral",hex:"#FF7759"},{name:"Violet",hex:"#D18EE2"}]},
  { name:"Mistral AI", industry:"AI", colors:[{name:"Orange",hex:"#FF6600"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"xAI", industry:"AI", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Jasper", industry:"AI", colors:[{name:"Coral Red",hex:"#FA4028"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Copy.ai", industry:"AI", colors:[{name:"Black",hex:"#131516"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Runway", industry:"AI", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"ElevenLabs", industry:"AI", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Character.AI", industry:"AI", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Inflection", industry:"AI", colors:[{name:"Cream",hex:"#FAF3EA"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Together AI", industry:"AI", colors:[{name:"Magenta",hex:"#EF2CC1"},{name:"Violet",hex:"#CAAEF5"},{name:"Orange",hex:"#FC4C02"},{name:"Blue",hex:"#1A56DB"}]},
  { name:"Groq", industry:"AI", colors:[{name:"Orange",hex:"#F55036"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  // === Cloud & Infrastructure ===
  { name:"AWS", industry:"Cloud", colors:[{name:"Orange",hex:"#FF9900"},{name:"Dark",hex:"#232F3E"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Google Cloud", industry:"Cloud", colors:[{name:"Blue",hex:"#4285F4"},{name:"Red",hex:"#EA4335"},{name:"Yellow",hex:"#FBBC04"},{name:"Green",hex:"#34A853"}]},
  { name:"Azure", industry:"Cloud", colors:[{name:"Blue",hex:"#0078D4"},{name:"Light Blue",hex:"#50E6FF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"DigitalOcean", industry:"Cloud", colors:[{name:"Blue",hex:"#0080FF"},{name:"Dark",hex:"#031B4E"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Snowflake", industry:"Cloud", colors:[{name:"Blue",hex:"#29B5E8"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Databricks", industry:"Cloud", colors:[{name:"Red",hex:"#FF3621"},{name:"Dark",hex:"#1B3139"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Linode/Akamai", industry:"Cloud", colors:[{name:"Blue",hex:"#0097D7"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Vultr", industry:"Cloud", colors:[{name:"Blue",hex:"#007BFC"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Render", industry:"Cloud", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Railway", industry:"Cloud", colors:[{name:"Purple",hex:"#7B68EE"},{name:"Dark",hex:"#0B0D0E"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Fastly", industry:"Cloud", colors:[{name:"Red",hex:"#FF0000"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Akamai", industry:"Cloud", colors:[{name:"Blue",hex:"#009BDE"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  // === Media & News ===
  { name:"The New York Times", industry:"Media", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"},{name:"Light Gray",hex:"#F7F7F7"}]},
  { name:"BBC", industry:"Media", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"},{name:"Red",hex:"#BB1919"}]},
  { name:"CNN", industry:"Media", colors:[{name:"Red",hex:"#CC0000"},{name:"Dark",hex:"#0C0C0C"},{name:"White",hex:"#FFFFFF"}]},
  { name:"The Guardian", industry:"Media", colors:[{name:"Blue",hex:"#052962"},{name:"Yellow",hex:"#FFE500"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Bloomberg", industry:"Media", colors:[{name:"Black",hex:"#000000"},{name:"Purple",hex:"#6024B0"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Reuters", industry:"Media", colors:[{name:"Orange",hex:"#FF8000"},{name:"Blue",hex:"#003366"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Medium", industry:"Media", colors:[{name:"Black",hex:"#000000"},{name:"Green",hex:"#1A8917"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Substack", industry:"Media", colors:[{name:"Orange",hex:"#FF6719"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#242424"}]},
  { name:"Vice", industry:"Media", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Vox", industry:"Media", colors:[{name:"Yellow",hex:"#FFF200"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"BuzzFeed", industry:"Media", colors:[{name:"Red",hex:"#EE3322"},{name:"Dark",hex:"#222222"},{name:"White",hex:"#FFFFFF"}]},
  { name:"The Verge", industry:"Media", colors:[{name:"Purple",hex:"#5200FF"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"TechCrunch", industry:"Media", colors:[{name:"Green",hex:"#0A9E01"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Wired", industry:"Media", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Associated Press", industry:"Media", colors:[{name:"Red",hex:"#CC0000"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Al Jazeera", industry:"Media", colors:[{name:"Gold",hex:"#C5963A"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Financial Times", industry:"Media", colors:[{name:"Salmon",hex:"#FCD0A1"},{name:"Dark",hex:"#1A1A1A"},{name:"Blue",hex:"#003780"}]},
  { name:"The Economist", industry:"Media", colors:[{name:"Red",hex:"#E3120B"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Wall Street Journal", industry:"Media", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Washington Post", industry:"Media", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Axios", industry:"Media", colors:[{name:"Dark",hex:"#1A1A1A"},{name:"Blue",hex:"#3B6BE3"},{name:"White",hex:"#FFFFFF"}]},
  { name:"The Atlantic", industry:"Media", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Politico", industry:"Media", colors:[{name:"Red",hex:"#CC0000"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Forbes", industry:"Media", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Business Insider", industry:"Media", colors:[{name:"Black",hex:"#000000"},{name:"Blue",hex:"#004DBD"},{name:"White",hex:"#FFFFFF"}]},
  // === Telecom ===
  { name:"AT&T", industry:"Telecom", colors:[{name:"Blue",hex:"#009FDB"},{name:"Dark Blue",hex:"#00244E"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Verizon", industry:"Telecom", colors:[{name:"Red",hex:"#CD040B"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"T-Mobile", industry:"Telecom", colors:[{name:"Magenta",hex:"#E20074"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Vodafone", industry:"Telecom", colors:[{name:"Red",hex:"#E60000"},{name:"White",hex:"#FFFFFF"},{name:"Dark",hex:"#1A1A1A"}]},
  { name:"Orange", industry:"Telecom", colors:[{name:"Orange",hex:"#FF7900"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Comcast", industry:"Telecom", colors:[{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"China Mobile", industry:"Telecom", colors:[{name:"Blue",hex:"#007CC3"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Airtel", industry:"Telecom", colors:[{name:"Red",hex:"#E40000"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Jio", industry:"Telecom", colors:[{name:"Blue",hex:"#0E3C9E"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"SK Telecom", industry:"Telecom", colors:[{name:"Red",hex:"#E51837"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Deutsche Telekom", industry:"Telecom", colors:[{name:"Magenta",hex:"#E20074"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"BT", industry:"Telecom", colors:[{name:"Purple",hex:"#5514B4"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Telstra", industry:"Telecom", colors:[{name:"Blue",hex:"#0099D4"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Rogers", industry:"Telecom", colors:[{name:"Red",hex:"#DA291C"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Bell Canada", industry:"Telecom", colors:[{name:"Blue",hex:"#0071BE"},{name:"Dark",hex:"#1A1A1A"},{name:"White",hex:"#FFFFFF"}]},

  // === Added 2026-07: colorful brands to rebalance the audited dataset ===
  { name:"United Colors of Benetton", industry:"Fashion", colors:[{name:"Benetton Green",hex:"#00A650"},{name:"Red",hex:"#ED1C24"},{name:"Yellow",hex:"#FFF200"},{name:"Blue",hex:"#0072BC"}]},
  { name:"Fila", industry:"Fashion", colors:[{name:"Navy",hex:"#002D62"},{name:"Red",hex:"#C8102E"}]},
  { name:"Lacoste", industry:"Fashion", colors:[{name:"Lacoste Green",hex:"#046A38"},{name:"Red",hex:"#DA291C"}]},
  { name:"Levi's", industry:"Fashion", colors:[{name:"Levi's Red",hex:"#C41230"},{name:"White",hex:"#FFFFFF"}]},
  { name:"LEGO", industry:"Retail", colors:[{name:"Red",hex:"#D01012"},{name:"Yellow",hex:"#FFD500"},{name:"Black",hex:"#000000"}]},
  { name:"Toys \"R\" Us", industry:"Retail", colors:[{name:"Blue",hex:"#0066CC"},{name:"Red",hex:"#ED1C24"},{name:"Orange",hex:"#F7941D"},{name:"Green",hex:"#00A651"}]},
  { name:"Canadian Tire", industry:"Retail", colors:[{name:"Red",hex:"#D52B1E"},{name:"Green",hex:"#046A38"}]},
  { name:"Sainsbury's", industry:"Retail", colors:[{name:"Orange",hex:"#F06C00"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Flipkart", industry:"E-commerce", colors:[{name:"Blue",hex:"#2874F0"},{name:"Yellow",hex:"#FFE11B"}]},
  { name:"Shopee", industry:"E-commerce", colors:[{name:"Shopee Orange",hex:"#EE4D2D"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Tokopedia", industry:"E-commerce", colors:[{name:"Tokopedia Green",hex:"#03AC0E"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Lazada", industry:"E-commerce", colors:[{name:"Orange",hex:"#F57224"},{name:"Navy",hex:"#0F146A"},{name:"Magenta",hex:"#FE4960"}]},
  { name:"McLaren", industry:"Automotive", colors:[{name:"Papaya Orange",hex:"#FF8000"},{name:"Anthracite",hex:"#47484A"}]},
  { name:"Renault", industry:"Automotive", colors:[{name:"Renault Yellow",hex:"#EFDF00"},{name:"Black",hex:"#000000"}]},
  { name:"Suzuki", industry:"Automotive", colors:[{name:"Red",hex:"#E30613"},{name:"Blue",hex:"#1B3F94"}]},
  { name:"Škoda", industry:"Automotive", colors:[{name:"Emerald Green",hex:"#0E3A2F"},{name:"Electric Green",hex:"#78FAAE"}]},
  { name:"Fanta", industry:"F&B", colors:[{name:"Fanta Orange",hex:"#FF8300"},{name:"Black",hex:"#000000"},{name:"White",hex:"#FFFFFF"}]},
  { name:"M&M's", industry:"F&B", colors:[{name:"Red",hex:"#DA291C"},{name:"Yellow",hex:"#FFD700"},{name:"Blue",hex:"#0057B8"},{name:"Green",hex:"#00A651"}]},
  { name:"Baskin-Robbins", industry:"F&B", colors:[{name:"Pink",hex:"#DA1884"},{name:"Blue",hex:"#006DB7"}]},
  { name:"easyJet", industry:"Travel", colors:[{name:"easyJet Orange",hex:"#FF6600"},{name:"Charcoal",hex:"#333333"}]},
  { name:"Trivago", industry:"Travel", colors:[{name:"Red",hex:"#E3403D"},{name:"Orange",hex:"#F48F00"},{name:"Blue",hex:"#007FAD"}]},
  { name:"Wizz Air", industry:"Travel", colors:[{name:"Wizz Pink",hex:"#C6007E"},{name:"Indigo",hex:"#06038D"}]},
  { name:"Gojek", industry:"Transport", colors:[{name:"Gojek Green",hex:"#00AA13"},{name:"Dark Green",hex:"#008700"}]},
  { name:"Deliveroo", industry:"Transport", colors:[{name:"Teal",hex:"#00CCBC"},{name:"Dark Teal",hex:"#00B8A9"}]},
  { name:"Swiggy", industry:"Transport", colors:[{name:"Swiggy Orange",hex:"#FC8019"},{name:"Dark Gray",hex:"#282C3F"}]},
  { name:"Zocdoc", industry:"Health", colors:[{name:"Zocdoc Yellow",hex:"#EEB111"},{name:"Charcoal",hex:"#333333"}]},
  { name:"Flo", industry:"Health", colors:[{name:"Coral Pink",hex:"#FF6E83"},{name:"Peach Orange",hex:"#FF9052"}]},
  { name:"Planet Fitness", industry:"Health", colors:[{name:"Purple",hex:"#5C2E91"},{name:"Yellow",hex:"#FFE011"}]},
  { name:"Pokémon", industry:"Gaming", colors:[{name:"Yellow",hex:"#FFCB05"},{name:"Blue",hex:"#3D7DCA"},{name:"Navy",hex:"#003A70"}]},
  { name:"Razer", industry:"Gaming", colors:[{name:"Razer Green",hex:"#44D62C"},{name:"Black",hex:"#000000"}]},
  { name:"Crunchyroll", industry:"Entertainment", colors:[{name:"Crunchyroll Orange",hex:"#F47521"},{name:"Dark Slate",hex:"#2B2B2B"}]},
  { name:"Nickelodeon", industry:"Entertainment", colors:[{name:"Nick Orange",hex:"#F57D0D"},{name:"White",hex:"#FFFFFF"}]},
  { name:"NBC", industry:"Media", colors:[{name:"Yellow",hex:"#FCB711"},{name:"Red",hex:"#CC004C"},{name:"Blue",hex:"#0089D0"},{name:"Green",hex:"#0DB14B"}]},
  { name:"Genius", industry:"Music", colors:[{name:"Genius Yellow",hex:"#FFFF64"},{name:"Black",hex:"#121212"}]},
  { name:"Last.fm", industry:"Music", colors:[{name:"Red",hex:"#D51007"},{name:"Dark Gray",hex:"#232323"}]},
  { name:"Flickr", industry:"Social", colors:[{name:"Blue",hex:"#0063DC"},{name:"Pink",hex:"#FF0084"}]},
  { name:"VK", industry:"Social", colors:[{name:"Azure Blue",hex:"#0077FF"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Binance", industry:"Fintech", colors:[{name:"Binance Yellow",hex:"#F0B90B"},{name:"Dark",hex:"#181A20"}]},
  { name:"Zelle", industry:"Fintech", colors:[{name:"Purple",hex:"#6D1ED4"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Payoneer", industry:"Fintech", colors:[{name:"Orange",hex:"#FF4800"},{name:"Charcoal",hex:"#404040"}]},
  { name:"MTN", industry:"Telecom", colors:[{name:"Yellow",hex:"#FFCB05"},{name:"Navy",hex:"#004F9F"}]},
  { name:"Telia", industry:"Telecom", colors:[{name:"Purple",hex:"#990AE3"},{name:"Deep Purple",hex:"#29003E"}]},
  { name:"SurveyMonkey", industry:"Marketing", colors:[{name:"Sabaeus Green",hex:"#00BF6F"},{name:"Charcoal",hex:"#333E48"}]},
  { name:"ActiveCampaign", industry:"Marketing", colors:[{name:"Blue",hex:"#356AE6"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Scratch", industry:"Education", colors:[{name:"Orange",hex:"#F9A83A"},{name:"Motion Blue",hex:"#4C97FF"},{name:"Looks Purple",hex:"#9966FF"}]},
  { name:"Babbel", industry:"Education", colors:[{name:"Orange",hex:"#FF7A00"},{name:"White",hex:"#FFFFFF"}]},
  { name:"Polaroid", industry:"Tech", colors:[{name:"Spectrum Blue",hex:"#0072CE"},{name:"Spectrum Green",hex:"#00A651"},{name:"Spectrum Yellow",hex:"#FFD100"},{name:"Spectrum Red",hex:"#E4002B"}]},
  { name:"Roku", industry:"Tech", colors:[{name:"Roku Purple",hex:"#662D91"},{name:"Magenta Accent",hex:"#FF1F8F"}]},
  { name:"Grafana", industry:"Dev Tools", colors:[{name:"Flame Orange",hex:"#F05A28"},{name:"Flame Yellow",hex:"#FADE2A"}]},
  { name:"JetBrains", industry:"Dev Tools", colors:[{name:"Orange",hex:"#FC801D"},{name:"Magenta",hex:"#FE2857"},{name:"Purple",hex:"#AF1DF5"}]},
  { name:"Vite", industry:"Dev Tools", colors:[{name:"Indigo",hex:"#646CFF"},{name:"Purple",hex:"#BD34FE"},{name:"Yellow",hex:"#FFDD35"},{name:"Amber",hex:"#FFA800"}]},
  { name:"Firebase", industry:"Cloud", colors:[{name:"Yellow",hex:"#FFC400"},{name:"Orange",hex:"#FF9100"},{name:"Flame Red",hex:"#DD2C00"}]},
  { name:"Pulumi", industry:"Cloud", colors:[{name:"Purple",hex:"#8A3391"},{name:"Salmon",hex:"#F26E7E"},{name:"Yellow",hex:"#F7BF2A"}]},
  { name:"Google Gemini", industry:"AI", colors:[{name:"Blue",hex:"#4285F4"},{name:"Purple",hex:"#9B72CB"},{name:"Coral",hex:"#D96570"}]},
  { name:"Kaggle", industry:"AI", colors:[{name:"Kaggle Cyan",hex:"#20BEFF"}]},
  { name:"DeepSeek", industry:"AI", colors:[{name:"DeepSeek Blue",hex:"#4D6BFE"}]},
  { name:"ClickUp", industry:"Productivity", colors:[{name:"Purple",hex:"#7B68EE"},{name:"Pink",hex:"#FD71AF"},{name:"Cyan",hex:"#49CCF9"},{name:"Yellow",hex:"#FFC800"}]},
  { name:"Zapier", industry:"Productivity", colors:[{name:"Zapier Orange",hex:"#FF4F00"},{name:"Night",hex:"#201515"}]},
  { name:"Evernote", industry:"Productivity", colors:[{name:"Evernote Green",hex:"#00A82D"},{name:"Dark Slate",hex:"#2E3338"}]},
  { name:"Blender", industry:"Design", colors:[{name:"Blender Orange",hex:"#EA7600"},{name:"Blender Blue",hex:"#265787"}]},
  { name:"Procreate", industry:"Design", colors:[{name:"Brush Teal",hex:"#35C9DD"},{name:"Brush Purple",hex:"#8E71DF"},{name:"Brush Pink",hex:"#E9539E"},{name:"Brush Orange",hex:"#F9A13D"}]},
  { name:"Affinity", industry:"Design", colors:[{name:"Affinity Green",hex:"#A7F175"},{name:"Black",hex:"#211D1D"}]},
];
